openapi: 3.0.3
info:
  title: Ebarimt POS API 3.0.1 (Local PosAPI)
  version: "3.0.1"
  description: |
    Contract specification for Mongolia Ebarimt POS API (PosAPI) v3.0.1.

    Notes:
    - This API typically runs on localhost or on an internal network segment accessible via VPN / security policy.
    - Monetary amounts are **tax-inclusive** as described in the POS API 3.0.1 documentation.
servers:
  - url: "http://{baseUrl}"
    variables:
      baseUrl:
        default: "127.0.0.1:7080"
tags:
  - name: receipt
    description: Receipt create / cancel
  - name: operations
    description: Operational endpoints
paths:
  /rest/receipt:
    post:
      tags: [receipt]
      operationId: createReceipt
      summary: Create (register) a receipt package and return DDTD, lottery and QR payload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReceiptCreateRequest"
      responses:
        "200":
          description: Receipt created (or error status returned by PosAPI)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReceiptCreateResponse"
        "400":
          description: Validation error (request rejected by PosAPI)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: PosAPI internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    delete:
      tags: [receipt]
      operationId: cancelReceipt
      summary: Cancel (return) a previously created receipt by DDTD and print date
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReceiptCancelRequest"
      responses:
        "204":
          description: Cancelled (no content)
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: PosAPI internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /rest/send:
    get:
      tags: [operations]
      operationId: sendToCentral
      summary: Trigger sending accumulated receipts from PosAPI to the central Ebarimt system
      responses:
        "204":
          description: Trigger accepted (no content)
        "500":
          description: PosAPI internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /rest/info:
    get:
      tags: [operations]
      operationId: getInfo
      summary: Get PosAPI operational information and registered merchants/customers
      responses:
        "200":
          description: Info payload
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"
        "500":
          description: PosAPI internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /rest/bankAccounts:
    get:
      tags: [operations]
      operationId: getBankAccounts
      summary: Get merchant/customer bank accounts by TIN
      parameters:
        - in: query
          name: tin
          required: true
          schema:
            type: string
            pattern: '^(\\d{11}|\\d{14})$'
          description: Merchant/Customer TIN (11 or 14 digits)
      responses:
        "200":
          description: List of bank accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BankAccount"
        "400":
          description: Validation error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: PosAPI internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    ReceiptCreateRequest:
      type: object
      additionalProperties: false
      required:
        - totalAmount
        - totalVAT
        - totalCityTax
        - districtCode
        - merchantTin
        - posNo
        - type
        - receipts
        - payments
      properties:
        totalAmount:
          type: number
          description: Package total amount (tax-inclusive)
        totalVAT:
          type: number
          description: Package total VAT amount
        totalCityTax:
          type: number
          description: Package total city tax amount
        districtCode:
          type: string
          description: District/region code (4 digits)
          pattern: '^(\\d{4})$'
        merchantTin:
          $ref: "#/components/schemas/TIN"
        posNo:
          type: string
          description: Merchant internal POS number
        customerTin:
          $ref: "#/components/schemas/TIN"
          nullable: true
        consumerNo:
          type: string
          description: ebarimt.mn consumer number (8 digits) or 11****** code for easy registration
          nullable: true
        type:
          $ref: "#/components/schemas/ReceiptType"
        inactiveId:
          $ref: "#/components/schemas/DDTD"
          nullable: true
          description: DDTD of the receipt being adjusted/partially returned
        invoiceId:
          $ref: "#/components/schemas/DDTD"
          nullable: true
          description: DDTD of a previously created invoice that is being paid
        reportMonth:
          type: string
          nullable: true
          description: Reporting month (yyyy-MM-dd)
          pattern: '^\\d{4}-\\d{2}-\\d{2}$'
        data:
          type: object
          nullable: true
          description: Additional package-level data (opaque JSON)
          additionalProperties: true
        receipts:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/SubReceiptCreate"
        payments:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/Payment"

    SubReceiptCreate:
      type: object
      additionalProperties: false
      required:
        - totalAmount
        - totalVAT
        - totalCityTax
        - taxType
        - merchantTin
        - items
      properties:
        totalAmount:
          type: number
        totalVAT:
          type: number
        totalCityTax:
          type: number
        taxType:
          $ref: "#/components/schemas/TaxType"
        merchantTin:
          $ref: "#/components/schemas/TIN"
        bankAccountNo:
          type: string
          nullable: true
          description: Bank account number (required for invoice types)
        data:
          type: object
          nullable: true
          description: Additional sub-receipt data (opaque JSON)
          additionalProperties: true
        items:
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/Item"

    Item:
      type: object
      additionalProperties: false
      required:
        - name
        - barCode
        - barCodeType
        - classificationCode
        - measureUnit
        - qty
        - unitPrice
        - totalVAT
        - totalCityTax
        - totalAmount
      properties:
        name:
          type: string
        barCode:
          type: string
          description: Product/service barcode (or empty if UNDEFINED)
        barCodeType:
          $ref: "#/components/schemas/BarCodeType"
        classificationCode:
          type: string
          description: Unified classification code (7 digits)
          pattern: '^\\d{7}$'
        taxProductCode:
          type: string
          nullable: true
          description: Tax product code (3 digits) required when taxType is VAT_FREE or VAT_ZERO
          pattern: '^\\d{3}$'
        measureUnit:
          type: string
        qty:
          type: number
        unitPrice:
          type: number
          description: Unit price (tax-inclusive)
        totalBonus:
          type: number
          nullable: true
        totalVAT:
          type: number
        totalCityTax:
          type: number
        totalAmount:
          type: number
          description: Line total amount (tax-inclusive)
        data:
          type: object
          nullable: true
          additionalProperties: true

    Payment:
      type: object
      additionalProperties: false
      required:
        - code
        - paidAmount
        - status
      properties:
        code:
          $ref: "#/components/schemas/PaymentCode"
        exchangeCode:
          type: string
          nullable: true
          description: Third-party payment system code
        status:
          $ref: "#/components/schemas/PaymentStatus"
        paidAmount:
          type: number
        data:
          type: object
          nullable: true
          additionalProperties: true

    ReceiptCreateResponse:
      type: object
      additionalProperties: true
      required:
        - id
        - posId
        - status
        - message
        - date
        - easy
        - receipts
      properties:
        id:
          $ref: "#/components/schemas/DDTD"
          description: Package receipt DDTD
        posId:
          type: number
        status:
          $ref: "#/components/schemas/ReceiptStatus"
        message:
          type: string
        qrData:
          type: string
          nullable: true
          description: QR code payload (must not be stored except printing)
        lottery:
          type: string
          nullable: true
          description: Lottery number (must not be stored except printing)
        date:
          type: string
          description: Print date (yyyy-MM-dd HH:mm:ss)
        easy:
          type: boolean
        receipts:
          type: array
          items:
            $ref: "#/components/schemas/SubReceiptResponse"

    SubReceiptResponse:
      type: object
      additionalProperties: true
      required:
        - id
      properties:
        id:
          $ref: "#/components/schemas/DDTD"
        bankAccountId:
          type: integer
          nullable: true

    ReceiptCancelRequest:
      type: object
      additionalProperties: false
      required:
        - id
        - date
      properties:
        id:
          $ref: "#/components/schemas/DDTD"
          description: Package receipt DDTD (33 digits)
        date:
          type: string
          description: Print date (yyyy-MM-dd HH:mm:ss)

    InfoResponse:
      type: object
      additionalProperties: false
      required:
        - operatorName
        - operatorTIN
        - posId
        - posNo
        - lastSentDate
        - leftLotteries
        - appInfo
        - merchants
      properties:
        operatorName:
          type: string
        operatorTIN:
          $ref: "#/components/schemas/TIN"
        posId:
          type: number
        posNo:
          type: string
        lastSentDate:
          type: string
          description: "yyyy-MM-dd HH:mm:ss"
        leftLotteries:
          type: integer
        appInfo:
          $ref: "#/components/schemas/AppInfo"
        merchants:
          type: array
          items:
            $ref: "#/components/schemas/Merchant"

    AppInfo:
      type: object
      additionalProperties: false
      required:
        - applicationDir
        - currentDir
        - database
        - database-host
        - workDir
      properties:
        applicationDir:
          type: string
        currentDir:
          type: string
        database:
          type: string
        database-host:
          type: string
        workDir:
          type: string

    Merchant:
      type: object
      additionalProperties: false
      required:
        - name
        - tin
        - customers
      properties:
        name:
          type: string
        tin:
          $ref: "#/components/schemas/TIN"
        customers:
          type: array
          items:
            $ref: "#/components/schemas/Customer"

    Customer:
      type: object
      additionalProperties: false
      required:
        - name
        - tin
      properties:
        name:
          type: string
        tin:
          $ref: "#/components/schemas/TIN"

    BankAccount:
      type: object
      additionalProperties: false
      required:
        - id
        - tin
        - bankAccountNo
        - bankAccountName
        - bankId
        - bankName
      properties:
        id:
          type: integer
        tin:
          $ref: "#/components/schemas/TIN"
        bankAccountNo:
          type: string
        bankAccountName:
          type: string
        bankId:
          type: integer
        bankName:
          type: string

    # --- shared primitives/enums ---
    DDTD:
      type: string
      description: DDTD (33 digits)
      pattern: '^\\d{33}$'

    TIN:
      type: string
      description: Taxpayer Identification Number (11 or 14 digits)
      pattern: '^(\\d{11}|\\d{14})$'

    ReceiptType:
      type: string
      enum: [B2C_RECEIPT, B2B_RECEIPT, B2C_INVOICE, B2B_INVOICE]

    ReceiptStatus:
      type: string
      enum: [SUCCESS, ERROR, PAYMENT]

    PaymentCode:
      type: string
      enum: [CASH, PAYMENT_CARD]

    PaymentStatus:
      type: string
      enum: [PAID, PAY, REVERSED, ERROR]

    TaxType:
      type: string
      enum: [VAT_ABLE, VAT_FREE, VAT_ZERO, NO_VAT]

    BarCodeType:
      type: string
      enum: [UNDEFINED, GS1, ISBN]

    ErrorResponse:
      type: object
      additionalProperties: true
      properties:
        status:
          type: string
        message:
          type: string
        code:
          type: string
          nullable: true
